function dplot(z,n,mapfunction,scalefunction)
figure(n)
colormap(mapfunction)
surf(z,scalefunction(z))
view(-30,30)
title('Danfoss Load Profile')
xlabel('Days from 6/9/15')
ylabel('Time of Day')
zlabel('KW Use')
endfunction