@startuml
entity CoolProp  #blue
control DataGrabber #red
control Data #green
boundary Plot #yellow
database Pandas #red
database CSV #green

autonumber
activate DataGrabber
DataGrabber -> DataGrabber: Initialize Memory Stores and program
autonumber 1
DataGrabber -> Pandas: Call Library
autonumber 1
DataGrabber -> CoolProp: Call Library
autonumber 2 1
activate Pandas
activate CoolProp
DataGrabber -> CoolProp: Request Data
CoolProp -> DataGrabber: Send Data
deactivate CoolProp
activate Data
DataGrabber -> Data: Create New List for Empty Data
Data -> Data: Trim Bad Data
Data -> Pandas: Store Data in Pandas Frame
deactivate Data
activate CSV
Pandas -> CSV: Write Data to CSV File
deactivate CSV
Pandas -> Plot: Plot Data
deactivate Pandas
activate Plot

Plot->Plot: Plot Shown on Screen
Plot->DataGrabber: On Close Signal Plot Close
deactivate Plot
DataGrabber -> DataGrabber: End


@enduml
